language: objective-c
osx_image: xcode8
before_install:
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
- gem update cocoapods
script:
- ./fastlane/travis.sh
notifications:
  email:
    on_sucess: never
