language: objective-c
cache:
- cocoapods
- bundler
osx_image: xcode8.2
before_install:
- echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
- gem install bundler
- bundle install
- bundle update
install: true
script:
- ./fastlane/travis.sh
notifications:
  email:
    on_sucess: never
