language: objective-c
osx_image: xcode8
xcode_workspace: MunchkinLevelCounter.xcworkspace
xcode_scheme: MunchkinLevelCounter
xcode_sdk: iphonesimulator
cache:
  - cocoapods
  - bundler
install:
  - bundle install --without=documentation
before_script:
  - export LANG=en_US.UTF-8
script:
  - bundle exec fastlane test
