language: objective-c
osx_image: xcode8
xcode_workspace: MunchkinLevelCounter.xcworkspace
xcode_scheme: MunchkinLevelCounter
xcode_sdk: iphonesimulator
script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME | xcpretty
