require "securerandom"

fastlane_version "1.109.0"

default_platform :ios

platform :ios do

  before_all do
    cocoapods
  end

  desc "Submit a new build of Munchkin Level Counter to Fabric Beta"
  lane :beta do

    skip_docs

    keychain_name = "munchkin"

    # Creating keychain
    create_keychain(
      name: keychain_name,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: SecureRandom.base64
    )

    # Import distribution certificate
    import_certificate(
      keychain_name: keychain_name,
      certificate_path: "fastlane/Certificates/datarockets.p12",
      certificate_password: ENV["KEY_PASSWORD"],
    )

    # Fetch or create provisioning profile
    sigh(
      adhoc: true,
      username: "chyrta@me.com",
      team_id: "M5MBYBFCK5",
      provisioning_name: "Munchkin Level Counter Ad Hoc Distribution",
      cert_id: "M5MBYBFCK5"
    )

    # Building an app
    gym(
      configuration: "Ad Hoc",
      sdk: "10.0",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      export_method: "ad-hoc"
    )

    # Pushing to Fabric Beta
    crashlytics(
      api_token: ENV["FABRIC_API_TOKEN"],
      build_secret: ENV["FABRIC_BUILD_SECRET"]
    )

    delete_keychain(
      name: keychain_name
    )

    # Post a message to opensource channel
    slack(
      message: "Munckin Level Counter was released",
      slack_url: "https://hooks.slack.com/services/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"
    )

    error do |lane, exception|
      delete_keychain(
        name: keychain_name
      )
    end

  end

end
